name: Example Workflow
on:
  push:
    branches: 
      - "main"

jobs:
  build:    # This workflow contains a single job called "build"
    runs-on: ubuntu-latest   # The type of runner that the job will run on
  
    steps:  # List of steps to be executed within the job
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!
